[[manager.prepend_keymap]]
on = [ "e" ]
run = [ '''
    shell 'echo "cd $@" | tmux load-buffer -' --confirm
''', "yank" ]
desc = "Yank to tmux buffer" 

[[manager.prepend_keymap]]
on = [ "g", "r" ]
run = '''
	shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
'''
desc = "cd back to the root of the git repo" 
